version: 2

builds:
  - id: specs
    main: .
    binary: specs
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - -s -w
      - -X github.com/specsnl/specs-cli/pkg/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]

archives:
  - format: tar.gz
    name_template: "specs_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: specsnl
    name: specs-cli
  draft: false
  prerelease: auto

brews:
  - name: specs
    repository:
      owner: specsnl
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/specsnl/specs-cli"
    description: "General-purpose developer CLI"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "specs"
    test: |
      system "#{bin}/specs", "version", "--dont-prettify"
