volumes:
  go-mod:
  go-build-cache:

services:
  go-builder:
    profiles: ["build"]
    build:
      context: .
      dockerfile: Dockerfile
      target: builder-download
    volumes:
      - .:/src
      - go-mod:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build

  go-binary:
    profiles: ["build"]
    build:
      context: .
      dockerfile: Dockerfile
      target: export
